version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    image: rice-analysis-platform-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  worker:
    image: rice-analysis-platform-backend:latest
    command: celery -A app.worker.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - redis

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:80" # Access the app via localhost:8080
    depends_on:
      - backend

volumes:
  postgres_data: